# Arquivo de configurações para o script CTRL_SmartCap.py
data_smartCAP:
  feeder_path: 'C:/SmartRT/feeders/'
  utility: '391' #'63'
  feeder:
    - 'RMTQ1302' #EDP-391
#    - 'ABR07'
#    - 'ABR08'
#    - 'ABR09'
#    - 'ABR10'
#    - 'ABR11'
#    - 'AER02'
#    - 'AER03'
#    - 'AER04'
#    - 'AER05'
#    - 'AGU07'
#    - 'AGU08'
#    - 'AGU09'
#    - 'AGU10'
#    - 'MBA13'
#    - 'MBA14'
#    - 'MBA15'
#    - 'MIR14'
#    - 'MIR15'
#    - 'MIR16'
#    - 'MIR21'
#    - 'MIR22'
#    - 'MIR23'
#    - 'MIR24'
#    - 'TAQ03'
#    - 'TAQ04'
#    - 'TAQ05'
#    - 'TAQ06'
#    - 'TAQ08'
#    - 'TAQ09'
#    - 'TAQ10'
#    - 'TAQ11'
#    - 'TAQ12'
#    - 'TAQ22'
#    - 'TAQ23'
#    - 'TAQ24'
#    - 'TAQ25'
#    - 'TAQ26'
  cenario:
#    - '1,Caso_Base'
    - '2,Caso_kvar'
#    - '3,Caso_tensao'
  controle:
#    - '0,Corrente'
#    - '1,Tensao'
#    - '2,kvar'
#    - '3,Tempo'
#    - '4,FP'
#    - '5,Fixo'
    - '6,Desligado'
  month: 7 #[1, 7]
  type_day: 'DU' #['DU', 'DO']
  num_patamares: 24
  patamar_ini: 0
  patamar_fim: 24
  multiprocess: False
